### ISSUE TITLE
Possibility of adding a :host option to synchronize timezone with the host

### ISSUE THREAD

**Issue by corbt** [tmatilai/vagrant-timezone#1]
Hello,

I need to keep my guest timezone in sync with the host timezone so that when parallels (my provider) syncs the guest's clock it isn't off by a multiple of hours.

I'm wondering if you'd be willing to add an option along the lines of `config.timezone.value = :host` or alternatively `config.timezone.match_host`. It could be implemented using a technique similar to the one found [here](https://coderwall.com/p/v8fr2g/a-quick-hack-to-set-the-timezone-for-a-vagrant-vm-in-ubuntu).

If that sounds fine to you, I'd be happy to submit a PR.

**Comment by tmatilai** [comment]
Hi Kyle,

This sounds like a great feature! A pull request would be great. The `:host` value for the current configuration key feels fine for me.
