### ISSUE TITLE
Does not work with systemd/timedatectl based guests

### ISSUE THREAD

**Issue by botzill** [tmatilai/vagrant-timezone#5]
Tested this with `Vagrant 2.0.0` and seems to not work, does it support this version?

**Comment by tmatilai** [comment]
There shouldn't be any reason why Vagrant 2.0 should not be supported, but I haven't tested it myself. How does it not work? Could you please gist the debug logs and all other useful information?

**Comment by azaghal** [comment]
Just ran into same issue here. What would be the best way to produce debug logs for the plugin? `VAGRANT_LOG=info` or `VAGRANT_LOG=debug`?

Host environment:

- Debian 9 (Stretch) x86_64
- Vagrant 2.0.1
- vagrant-timezone (1.2.0)
- Oracle VirtualBox 5.1.30r118389

Reproduction steps:

1. Verify Vagrant version is 2.0.1:

       vagrant --version

2. Install the `vagrant-timezone` plugin:

       vagrant plugin install vagrant-timezone

3. Set-up dedicated directory for running the test:

       mkdir -p ~/projects/test-vagrant-timezone

4. Set-up Vagrantfile with timezone configuration in `~/projects/test-vagrant-timezone/Vagrantfile`:

       Vagrant.configure("2") do |config|
         config.timezone.value = "Europe/Stockholm"
         config.vm.box = "debian/stretch64"
       end

5. Bring up the machine:

       cd ~/projects/test-vagrant-timezone/
       vagrant up

6. Check timezone reported by the OS and settings stored in `/etc/timezone`:

       cd ~/projects/test-vagrant-timezone/
       vagrant ssh -c 'date'
       vagrant ssh -c 'cat /etc/timezone'

Expected results:

1. Reported output is (notice the CET and Europe/Stockholm):

       Mon Nov 27 16:23:47 CET 2017
       Connection to 127.0.0.1 closed.
       
       Europe/Stockholm
       Connection to 127.0.0.1 closed.

Actual results:

1. Reported output is (notice the GMT and Etc/GMT+0):

       Mon Nov 27 15:22:58 GMT 2017
       Connection to 127.0.0.1 closed.

       Etc/GMT+0
       Connection to 127.0.0.1 closed.

**Comment by azaghal** [comment]
Hm... I'm actually starting to think that this is related to Debian Stretch (on box), and not to Vagrant 2. I can't seem to change timezone by updating `/etc/timezone` and running `dpkg-reconfigure` it seems (as outlined in `lib/vagrant-timezone/cap/debian.rb`).

**Comment by azaghal** [comment]
Ok... I think I finally got it. So, at least on Debian 9 (possibly anything that uses systemd), the correct way is to use the `timedatectl` binary. E.g:

```
timedatectl set-timezone Europe/Stockholm
```

This will, in turn, update symlink at location `/etc/localtime`. Not sure what would be the best approach to implement this (in terms of support for non-systemd variants).

**Comment by tmatilai** [comment]
Maybe add some `timedatectl?` (check the existence) and `timedatectl` (sets the timezone) cababilities to all Linux archs. Then check and use those in the `SetTimeZone` actions before falling back to `change_timezone`. It's been so long since I last touched Vagrant or plugin code that can't tell without playing a bit around. PRs welcome. ;)

**Comment by tmatilai** [comment]
Latest attempt to fix this in #10

**Comment by tmatilai** [comment]
Version 1.3.0 with the fix released
