### ISSUE TITLE
Uses invalid method for Redhat systems

### ISSUE THREAD

**Issue by alkuzad** [tmatilai/vagrant-timezone#6]
`Note that the ZONE parameter is read by the Time and Date Properties Tool (system-config-date), and manually editing it does not change the system timezone`

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/5/html/deployment_guide/ch-sysconfig

timedatectl seems to be correct method for system timezone setting

**Comment by tmatilai** [comment]
I think this is duplicate for #5
